#!/usr/bin/env bash
set -euo pipefail

# Run this once from a terminal opened in the active GNOME desktop. It records
# the short-lived display/session variables so an SSH restart can launch in the
# exact same graphical session.

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_DIR="${DIR}/data"
OUTPUT_FILE="${DESKTOP_ENV_FILE:-${RUN_DIR}/desktop.env}"

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "Desktop session capture is supported only on Linux." >&2
  exit 1
fi

if [[ -z "${DISPLAY:-}" && -z "${WAYLAND_DISPLAY:-}" ]]; then
  echo "No graphical display is available in this terminal." >&2
  echo "Open a terminal from GNOME and run this command there." >&2
  exit 1
fi

mkdir -p "${RUN_DIR}"
umask 077
{
  echo "# Generated by capture_desktop_session.sh. Do not commit this file."
  for variable in DISPLAY XAUTHORITY WAYLAND_DISPLAY XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS XDG_SESSION_TYPE XDG_CURRENT_DESKTOP MOZ_ENABLE_WAYLAND GDK_BACKEND; do
    value="${!variable:-}"
    [[ -n "${value}" ]] && printf 'export %s=%q\n' "${variable}" "${value}"
  done
} > "${OUTPUT_FILE}"

echo "Captured desktop session environment: ${OUTPUT_FILE}"
