#!/usr/bin/env bash
set -euo pipefail

# Restart the automation runner by freeing the configured port then running npm start.
# Modes:
# - --local: scripts, manual runs, and MCP without PostgreSQL.
# - --full: PostgreSQL-backed API Builder, proxy pools, and managed profiles.
# Port priority:
# 1) CLI arg: ./restart.sh 4300 OR ./restart.sh --port 4300
# 2) PORT env var
# 3) config.ini port
# 4) random free port persisted to config.ini

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CFG_FILE="${DIR}/config.ini"
RUN_DIR="${DIR}/data"
PID_FILE="${RUN_DIR}/server.pid"
LOG_FILE="${RUN_DIR}/server.log"
LOCAL_ENV_FILE="${LOCAL_ENV_FILE:-${RUN_DIR}/local.env}"
CAMOUFOX_HOME_DIR="${CAMOUFOX_HOME_DIR:-${RUN_DIR}/camoufox-home}"
DESKTOP_ENV_FILE="${DESKTOP_ENV_FILE:-${RUN_DIR}/desktop.env}"
PORT_FROM_ARG=""
PORT="${PORT:-}"
FORCE_XVFB="${FORCE_XVFB:-0}"
DAEMON_MODE="${DAEMON_MODE:-1}"
LOCAL_MODE="${LOCAL_MODE:-0}"
USE_DESKTOP="${USE_DESKTOP:-0}"

playwright_platform_override() {
  local version arch
  [[ -r /etc/os-release ]] || return 0
  # shellcheck disable=SC1091
  source /etc/os-release
  version="${VERSION_ID:-}"
  arch="$(dpkg --print-architecture)"
  if [[ "${ID:-}" == "ubuntu" && "${version%%.*}" -ge 26 && "${arch}" == "amd64" ]]; then
    echo "ubuntu24.04-x64"
  fi
}

load_local_database_url() {
  local database_url
  [[ -n "${DATABASE_URL:-}" || ! -f "${LOCAL_ENV_FILE}" ]] && return 0
  database_url="$(sed -n -E 's/^DATABASE_URL=(.*)$/\1/p' "${LOCAL_ENV_FILE}" | tail -n1)"
  [[ -n "${database_url}" ]] && export DATABASE_URL="${database_url}"
}

ensure_camoufox_install() {
  local version_file="${CAMOUFOX_HOME_DIR}/.cache/camoufox/version.json"
  if [[ -s "${version_file}" ]]; then
    return 0
  fi

  echo "Camoufox cache is missing or incomplete. Downloading the project-scoped binary..."
  HOME="${CAMOUFOX_HOME_DIR}" node "${DIR}/node_modules/camoufox-js/dist/__main__.js" fetch

  if [[ ! -s "${version_file}" ]]; then
    echo "Camoufox fetch completed without ${version_file}." >&2
    exit 1
  fi
}

desktop_session_value() {
  local name="$1"
  local process pid value

  for process in gnome-shell gnome-session-binary gnome-session; do
    while IFS= read -r pid; do
      [[ -r "/proc/${pid}/environ" ]] || continue
      value="$(tr '\0' '\n' < "/proc/${pid}/environ" | sed -n "s/^${name}=//p" | head -n1)"
      if [[ -n "${value}" ]]; then
        printf '%s\n' "${value}"
        return 0
      fi
    done < <(pgrep -u "$(id -u)" -x "${process}" 2>/dev/null || true)
  done
  return 1
}

load_captured_desktop_environment() {
  [[ -r "${DESKTOP_ENV_FILE}" ]] || return 1

  # This file is generated by capture_desktop_session.sh and contains only
  # desktop-session environment assignments owned by the current user.
  # shellcheck disable=SC1090
  source "${DESKTOP_ENV_FILE}"

  if [[ -d "${XDG_RUNTIME_DIR:-}" && ( -n "${DISPLAY:-}" || -n "${WAYLAND_DISPLAY:-}" ) ]]; then
    echo "Using captured desktop session environment from ${DESKTOP_ENV_FILE}."
    return 0
  fi

  echo "Captured desktop environment is stale; discovering the active GNOME session." >&2
  return 1
}

prepare_desktop_environment() {
  local user_id runtime_dir wayland_socket wayland_display xwayland_pid xwayland_args x_display x_authority x_socket

  [[ "$(uname -s)" == "Linux" ]] || {
    echo "--desktop is supported only on Linux." >&2
    exit 1
  }

  if load_captured_desktop_environment; then
    FORCE_XVFB="0"
    return 0
  fi

  user_id="$(id -u)"
  runtime_dir="$(desktop_session_value XDG_RUNTIME_DIR || true)"
  runtime_dir="${runtime_dir:-/run/user/${user_id}}"
  if [[ ! -d "${runtime_dir}" ]]; then
    echo "No active desktop runtime directory for user $(id -un): ${runtime_dir}" >&2
    echo "Connect over SSH as the same user that is logged in to GNOME." >&2
    exit 1
  fi

  wayland_display="$(desktop_session_value WAYLAND_DISPLAY || true)"
  if [[ -z "${wayland_display}" ]]; then
    for wayland_socket in "${runtime_dir}"/wayland-*; do
      [[ -S "${wayland_socket}" ]] || continue
      wayland_display="${wayland_socket##*/}"
      break
    done
  fi

  xwayland_pid="$(pgrep -u "${user_id}" -x Xwayland 2>/dev/null | head -n1 || true)"
  if [[ -n "${xwayland_pid}" && -r "/proc/${xwayland_pid}/cmdline" ]]; then
    xwayland_args="$(tr '\0' ' ' < "/proc/${xwayland_pid}/cmdline")"
  else
    xwayland_args=""
  fi
  x_display="$(awk '{ for (i = 1; i <= NF; i++) if ($i ~ /^:[0-9]+$/) { print $i; exit } }' <<< "${xwayland_args}")"
  x_authority="$(awk '{ for (i = 1; i < NF; i++) if ($i == "-auth") { print $(i + 1); exit } }' <<< "${xwayland_args}")"

  if [[ -z "${x_display}" ]]; then
    for x_socket in /tmp/.X11-unix/X*; do
      [[ -S "${x_socket}" ]] || continue
      x_display=":${x_socket##*/X}"
      break
    done
  fi

  if [[ -z "${x_display}" && -z "${wayland_display}" ]]; then
    echo "No active GNOME Wayland or X11 display was found for user $(id -un)." >&2
    echo "Log in to the graphical desktop first, then run this command through SSH as that user." >&2
    exit 1
  fi

  export XDG_RUNTIME_DIR="${runtime_dir}"
  local manager_dbus manager_display manager_xauthority
  manager_dbus="$(systemctl --user show-environment 2>/dev/null | sed -n 's/^DBUS_SESSION_BUS_ADDRESS=//p' | head -n1 || true)"
  manager_display="$(systemctl --user show-environment 2>/dev/null | sed -n 's/^DISPLAY=//p' | head -n1 || true)"
  manager_xauthority="$(systemctl --user show-environment 2>/dev/null | sed -n 's/^XAUTHORITY=//p' | head -n1 || true)"
  export DBUS_SESSION_BUS_ADDRESS="${manager_dbus:-$(desktop_session_value DBUS_SESSION_BUS_ADDRESS || true)}"
  export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=${runtime_dir}/bus}"

  if [[ -n "${manager_display}" ]]; then
    x_display="${manager_display}"
  fi
  if [[ -n "${manager_xauthority}" && -r "${manager_xauthority}" ]]; then
    x_authority="${manager_xauthority}"
  fi

  if [[ -n "${wayland_display}" ]]; then
    export WAYLAND_DISPLAY="${wayland_display}"
    export XDG_SESSION_TYPE="wayland"
    export MOZ_ENABLE_WAYLAND="1"
  fi
  if [[ -n "${x_display}" ]]; then
    export DISPLAY="${x_display}"
  else
    unset DISPLAY
  fi
  if [[ -n "${x_authority}" && -r "${x_authority}" ]]; then
    export XAUTHORITY="${x_authority}"
  elif [[ -r "${HOME}/.Xauthority" ]]; then
    export XAUTHORITY="${HOME}/.Xauthority"
  else
    unset XAUTHORITY
  fi

  FORCE_XVFB="0"
  echo "Using active desktop session: display=${DISPLAY:-Wayland}, wayland=${WAYLAND_DISPLAY:-off}."
}

read_port_from_config() {
  [[ -f "${CFG_FILE}" ]] || return 0
  grep -E '^port[[:space:]]*=' "${CFG_FILE}" | tail -n1 | sed -E 's/[^0-9]*([0-9]+).*/\1/' || true
}

is_port_in_use() {
  local p="$1"
  lsof -ti tcp:"${p}" >/dev/null 2>&1
}

is_valid_port() {
  local p="$1"
  [[ "${p}" =~ ^[0-9]+$ ]] && (( p >= 1 && p <= 65535 ))
}

pick_random_free_port() {
  local tries=200
  local p
  while (( tries > 0 )); do
    p=$(( (RANDOM % 35000) + 20000 ))
    if ! is_port_in_use "${p}"; then
      echo "${p}"
      return 0
    fi
    tries=$((tries - 1))
  done
  return 1
}

persist_port_to_config() {
  local p="$1"
  if [[ -f "${CFG_FILE}" ]] && grep -qE '^port[[:space:]]*=' "${CFG_FILE}"; then
    sed -E -i.bak "s/^port[[:space:]]*=.*/port=${p}/" "${CFG_FILE}"
    rm -f "${CFG_FILE}.bak"
  else
    {
      [[ -f "${CFG_FILE}" ]] && cat "${CFG_FILE}"
      echo "port=${p}"
    } > "${CFG_FILE}.tmp"
    mv "${CFG_FILE}.tmp" "${CFG_FILE}"
  fi
}

# Parse CLI args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)
      if [[ $# -lt 2 ]]; then
        echo "Usage: $0 [PORT | --port PORT] [--local|--full] [--desktop|--xvfb] [--daemon|--foreground]" >&2
        exit 1
      fi
      PORT_FROM_ARG="$2"
      shift 2
      ;;
    --xvfb)
      FORCE_XVFB="1"
      shift
      ;;
    --no-xvfb)
      FORCE_XVFB="0"
      shift
      ;;
    --desktop)
      USE_DESKTOP="1"
      shift
      ;;
    --local)
      LOCAL_MODE="1"
      shift
      ;;
    --full)
      LOCAL_MODE="0"
      shift
      ;;
    --daemon)
      DAEMON_MODE="1"
      shift
      ;;
    --foreground)
      DAEMON_MODE="0"
      shift
      ;;
    *)
      PORT_FROM_ARG="$1"
      shift
      ;;
  esac
done

if [[ -n "${PORT_FROM_ARG}" ]]; then
  if ! is_valid_port "${PORT_FROM_ARG}"; then
    echo "Invalid port: ${PORT_FROM_ARG}. Expected 1-65535." >&2
    exit 1
  fi
  PORT="${PORT_FROM_ARG}"
  persist_port_to_config "${PORT}"
  echo "Using CLI port: ${PORT}"
fi

if [[ -z "${PORT}" ]]; then
  cfg_port="$(read_port_from_config)"
  if [[ -n "${cfg_port}" ]]; then
    PORT="${cfg_port}"
  else
    PORT="$(pick_random_free_port)"
    persist_port_to_config "${PORT}"
    echo "No port configured. Picked random static port: ${PORT}"
  fi
fi

# Final fallback (very unlikely)
PORT="${PORT:-4000}"

echo "Stopping any process on port ${PORT}..."
if is_port_in_use "${PORT}"; then
  lsof -ti tcp:"${PORT}" | xargs kill -9 || true
  sleep 1
else
  echo "No process found on ${PORT}"
fi

echo "Starting server on port ${PORT}..."
cd "${DIR}"
mkdir -p "${RUN_DIR}"
mkdir -p "${CAMOUFOX_HOME_DIR}"
load_local_database_url
ensure_camoufox_install
if [[ "${USE_DESKTOP}" == "1" || "${USE_DESKTOP}" == "true" || "${USE_DESKTOP}" == "TRUE" ]]; then
  prepare_desktop_environment
fi

PLAYWRIGHT_PLATFORM_OVERRIDE="$(playwright_platform_override)"
START_CMD=(env PORT="${PORT}" LOCAL_MODE="${LOCAL_MODE}" "CAMOUFOX_HOME_DIR=${CAMOUFOX_HOME_DIR}" npm start)
if [[ -n "${PLAYWRIGHT_PLATFORM_OVERRIDE}" ]]; then
  START_CMD=(env PORT="${PORT}" LOCAL_MODE="${LOCAL_MODE}" "CAMOUFOX_HOME_DIR=${CAMOUFOX_HOME_DIR}" "PLAYWRIGHT_HOST_PLATFORM_OVERRIDE=${PLAYWRIGHT_PLATFORM_OVERRIDE}" npm start)
  echo "Using Playwright ${PLAYWRIGHT_PLATFORM_OVERRIDE} compatibility mode."
fi
if [[ "${LOCAL_MODE}" == "1" || "${LOCAL_MODE}" == "true" || "${LOCAL_MODE}" == "TRUE" ]]; then
  echo "Local mode enabled: PostgreSQL-backed API Builder features are disabled."
fi
if [[ "${USE_DESKTOP}" != "1" && "${USE_DESKTOP}" != "true" && "${USE_DESKTOP}" != "TRUE" && "$(uname -s)" == "Linux" && ( "${FORCE_XVFB}" == "1" || -z "${DISPLAY:-}" ) ]]; then
  if command -v xvfb-run >/dev/null 2>&1; then
    START_CMD=(xvfb-run -a -s "-screen 0 1920x1080x24 -ac +extension RANDR" "${START_CMD[@]}")
    echo "Starting with xvfb-run..."
  else
    echo "No DISPLAY detected and xvfb-run is missing." >&2
    echo "Install it with: sudo apt-get update && sudo apt-get install -y xvfb" >&2
    exit 1
  fi
fi

if [[ "${DAEMON_MODE}" == "1" ]]; then
  : > "${LOG_FILE}"
  nohup "${START_CMD[@]}" >> "${LOG_FILE}" 2>&1 &
  APP_PID="$!"
  echo "${APP_PID}" > "${PID_FILE}"
  sleep 1
  echo "Server started in background."
  echo "PID: ${APP_PID}"
  echo "Log: ${LOG_FILE}"
  echo "URL: http://localhost:${PORT}"
  exit 0
fi

exec "${START_CMD[@]}"
